name: Firebase Live Deployment
on: 
  pull_request:
      types: closed
      branches: main
    
jobs:
  deploy_live:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm install --no-save
      - name: Run clean
        run: npm run clean
      - name: Run build
        run: npm run build
      - name: Run export
        run: npm run export
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAPPLY_PWA }}"
          projectId: tapply-pwa
          channelId: live
   
